# -*- coding:utf-8 -*-
from zz_include import error_code

print(error_code["succeed"])

